# Generated by Django 2.0.2 on 2018-03-06 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('paswd', models.CharField(max_length=25)),
                ('set_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'adminu',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('conten', models.TextField()),
                ('set_time', models.DateTimeField(auto_now_add=True)),
                ('authon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.AdminU')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typename', models.CharField(max_length=25)),
                ('set_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conten', models.CharField(max_length=500)),
                ('set_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('paswd', models.CharField(max_length=25)),
                ('emila', models.EmailField(max_length=254)),
                ('set_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.ArticleType'),
        ),
    ]
