INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (4, 'Can add permission', 2, 'add_permission');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (5, 'Can change permission', 2, 'change_permission');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (6, 'Can delete permission', 2, 'delete_permission');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (7, 'Can add group', 3, 'add_group');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (8, 'Can change group', 3, 'change_group');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (9, 'Can delete group', 3, 'delete_group');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (10, 'Can add user', 4, 'add_user');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (11, 'Can change user', 4, 'change_user');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (12, 'Can delete user', 4, 'delete_user');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (13, 'Can add content type', 5, 'add_contenttype');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (14, 'Can change content type', 5, 'change_contenttype');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (15, 'Can delete content type', 5, 'delete_contenttype');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (16, 'Can add session', 6, 'add_session');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (17, 'Can change session', 6, 'change_session');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (18, 'Can delete session', 6, 'delete_session');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (19, 'Can add admin u', 7, 'add_adminu');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (20, 'Can change admin u', 7, 'change_adminu');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (21, 'Can delete admin u', 7, 'delete_adminu');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (22, 'Can add article', 8, 'add_article');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (23, 'Can change article', 8, 'change_article');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (24, 'Can delete article', 8, 'delete_article');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (25, 'Can add article type', 9, 'add_articletype');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (26, 'Can change article type', 9, 'change_articletype');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (27, 'Can delete article type', 9, 'delete_articletype');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (28, 'Can add comment', 10, 'add_comment');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (29, 'Can change comment', 10, 'change_comment');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (30, 'Can delete comment', 10, 'delete_comment');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (31, 'Can add user', 11, 'add_user');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (32, 'Can change user', 11, 'change_user');
INSERT INTO `auth_permission`(`id`, `name`, `content_type_id`, `codename`) VALUES (33, 'Can delete user', 11, 'delete_user');
